config/routes.rb
Rails.application.routes.draw do
  get 'homes/show'
  resources :homes, only: [:show]

  get 'welcome/index'
  resources :cheerups do
    resources :comments
  end

  resources :topics do
    member do
      post 'upvote'
    end
  end

  root to: "homes#show"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :cheerup
  # it would be nice to also have some validations on comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
def index
  @authentications = current_user.authentications if current_user
end

def create
  auth = request.env["rack.auth"]
  current_user.authentications.find_or_create_by_provider_and_uid(auth['provider'], auth['uid'])
  flash[:notice] = "Authentication successful."
  redirect_to authentications_url
end

def destroy
  @authentication = current_user.authentications.find(params[:id])
  @authentication.destroy
  flash[:notice] = "Successfully destroyed authentication."
  redirect_to authentications_url
end

app/controllers/cheerups_controller.rb
class CheerupsController < ApplicationController

  def index
    @cheerups = Cheerup.all
  end

  def edit
    @cheerup = Cheerup.find(params[:id])
  end


  def create
    @cheerup = Cheerup.new(cheerup_params)

    if @cheerup.save
      redirect_to cheerups_path
    else
      render 'new'
    end
  end

  def update
    @cheerup = Cheerup.find(params[:id])

    if @cheerup.update(cheerup_params)
      redirect_to cheerups_path
    else
      render 'edit'
    end
  end


  def new
    @cheerup = Cheerup.new
  end

  def show
    @cheerup = Cheerup.find(params[:id])
  end

  def destroy
  @cheerup = Cheerup.find(params[:id])
  @cheerup.destroy

  redirect_to cheerups_path
  end


  private
  def cheerup_params
    params.require(:cheerup).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @cheerup = Cheerup.find(params[:cheerup_id])
    @comment = @cheerup.comments.create(comment_params)
    redirect_to cheerup_path(@cheerup)
    # some sort of error handling like you have for cheerups that would take advantage of validations might be nice.
  end

  # you don't always have to give users the ability to edit/update but it's often nice if they create something that they didn't like they have an option besides simply deleting and starting over


  def destroy
    @cheerup = Cheerup.find(params[:cheerup_id])
    @comment = @cheerup.comments.find(params[:id])
    @comment.destroy
    redirect_to cheerup_path(@cheerup)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/concerns/authentications_controller.rb
def index
  @authentications = current_user.authentications if current_user
end

def create
  auth = request.env["rack.auth"]
  current_user.authentications.find_or_create_by_provider_and_uid(auth['provider'], auth['uid'])
  flash[:notice] = "Authentication successful."
  redirect_to authentications_url
end

def destroy
  @authentication = current_user.authentications.find(params[:id])
  @authentication.destroy
  flash[:notice] = "Successfully destroyed authentication."
  redirect_to authentications_url
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/links_controller.rb
def upvote
  @link = Link.find(params[:id])
  @link.upvote_by current_user
  redirect_to links_path
end

def downvote
  @link = Link.find(params[:id])
  @link.downvote_by current_user
  redirect_to links_path
end

app/controllers/topics_controller.rb
# Not sure why this is empty

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  if @user.save
    redirect_to cheerups_path, notice: "Signed Up Successfully!"
  else
    render :new
  end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheerups_helper.rb
module CheerupsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authentications/index.html.erb
<% title "Sign In" %>

<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You can sign in to this account using:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <%= image_tag "#{authentication.provider}_32.png", :size => "32x32" %>
          <div class="provider"><%= authentication.provider.titleize %></div>
          <div class="uid"><%= authentication.uid %></div>
          <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>

<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>
  Twitter
</a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>
  Facebook
</a>
<a href="/auth/google_apps" class="auth_provider">
  <%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>
  Google
</a>
<a href="/auth/open_id" class="auth_provider">
  <%= image_tag "openid_64.png", :size => "64x64", :alt => "OpenID" %>
  OpenID
</a>
<div class="clear"></div>

app/views/cheerups/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.cheerup, comment],
               method: :delete %>
</p>
<!-- nice use of partials -->

app/views/cheerups/_form.html.erb
<%= form_for([@cheerup, @cheerup.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cheerups/edit.html.erb
<h1> Edit Cheerup </h1>

<%= form_for :cheerup, url: cheerup_path(@cheerup), method: :patch do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', cheerups_path %>

app/views/cheerups/index.html.erb
<%= link_to 'Make New Cheerup', new_cheerup_path %>
<h1>Smile!!!! :)</h1>

<table>
  <tr>
    <!-- <th>Cheerup</th>
    <th>Cheerup Content</th> -->
    <th colspan="2"></th>
  </tr>

  <% @cheerups.each do |cheerup| %>

      <h1><%= cheerup.title %></h1>
      <h2><%= cheerup.text %></h2>
    <nav>
      <h3><%= link_to 'Rank this Cheerup', cheerup_path(cheerup) %></h3>
      <h3><%= link_to 'Make this Cheerup more awesome', edit_cheerup_path(cheerup) %></h3>
      <h3><%= link_to 'Delete this cheerup, it did not cheer me up', cheerup_path(cheerup),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></h3>
    </nav>
    </tr>
<% end %>
</table>

app/views/cheerups/new.html.erb
<h1> Cheerup! </h1>

<div>
<%= form_for @cheerup do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
</div>
<% end %>

<%= link_to 'Back', cheerups_path %>

app/views/cheerups/show.html.erb
<p>
  <strong>Cheerup:</strong>
  <%= @cheerup.title %>
</p>

<p>
  <strong>Cheered up:</strong>
  <%= @cheerup.text %>
</p>
<%= social_share_button_tag("Share a cheerup on FB & Twitter") %>
<h2>Comment on this cheerup</h2>
<%= render @cheerup.comments %>

<h2>Add a comment:</h2>
<%= render 'form' %>


<%= link_to 'Back', cheerups_path %>
<%= link_to 'Edit', edit_cheerup_path(@cheerup) %>
<%= social_share_button_tag("Share a cheerup on FB & Twitter") %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Delete this comment', [comment.cheerup, comment],
               method: :delete %>
</p>

app/views/comments/show.html.erb
<h3>Comments</h3>
<%= render @cheerup.comments %>

<h2>Add a comment:</h2>
<%= render 'form' %>


<%= link_to 'Back', cheerups_path %>
<%= link_to 'Edit', edit_cheerup_path(@cheerup) %>

app/views/homes/show.html.erb
<h1>Cheerups!!</h1>
<h2>The sun is out today! Smile!</h2>
<%= social_share_button_tag("Share a cheerup on FB & Twitter") %>
<%= link_to 'Make this world better by sharing a message that makes someone happy', controller: 'cheerups' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cheerups</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= image_tag ("http://cabrerainsights.com/wp-content/uploads/2015/10/To-happy-sign.jpg") %>

  <ul>
  <li><a href="#home">Home</a></li>
  <li><a href="http://www.happynews.com/">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li style="float:right"><a class="active" href="#about">About</a></li>
</ul>



<%= yield %>

</body>
</html>

app/views/links/index.html.slim
  @links.each do |link|
  = link_to "upvote", like_link_path(link), method: :put

  = link_to "downvote", dislike_link_path(link), method: :put

  = link.score

app/views/topics/index.html.erb
<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= topic.text %></td>
    <td><%= pluralize(topic.votes.count, "vote") %></td>
    <td><%= button_to '+1', upvote_topic_path(topic), method: :post %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<%= form_for @user do |f| %>

<% if @user.errors.any? %>
<div id="error-messages">
  <% @user.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
</div>
<% end %>

<%= f.label :email %>
<%= f.text_field :email%>

<%= f.label :password %>
<%= f.password_field :password%>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation%>

<% f.submit %>
<% end %>

app/views/welcome/index.html.erb
<h1>The sun is out today! Smile!</h1>
<%= link_to 'Make this world better by sharing a message that makes someone happy', controller: 'cheerups' %>